last_pid = 1604904
last_item_name = "BUTY X3X135 XF587-Q516-38"
last_item_slug = "buty-x3x135-xf587-q516-38"
webhooks = [ "https://discord.com/api/webhooks/631728334270758931/vVwflc7dOQ2_bzyfCuKl4DjakObBIVKYncLl-sQEmoKdD-shqnEitY8uLcwuMpU2U3Kh",]
